### ISSUE TITLE
A question about wiredtiger

### ISSUE THREAD

**Issue by lu6zhi6gan** [FavorLabs/favorX#47]
When I install, the following error occurs:
![QQ图片20220824151924](https://user-images.githubusercontent.com/71998320/186355876-c208a1ee-cfa0-42db-9cab-2f07ea2acb72.png)

**Comment by archibaldFL** [comment]
u can find this dll in windows release zip file.

**Comment by lu6zhi6gan** [comment]
I searched the Internet for this document, but I couldn't find it

**Comment by archibaldFL** [comment]
> I searched the Internet for this document, but I couldn't find it

you can use leveldb for favorX , please read configration doc
